[package]
name = "proc-win-etw-manifest"
version = "0.1.0"
edition = "2021"
authors = ["Marvin Gudel <github.marvin@gudel.org>"]
license = "MIT"
description = "Proc-macro crate to generate rust code for Microsoft Windows instrumentation manifests."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = "2.0.39"
uuid = "1.6.1"
win-etw-manifest = { git = "ssh://git@github.com/internet-sicherheit/win-etw-manifest-rs.git" }

