//! Events generated by manifest based providers and their associated types

pub mod xed2;

use std::{
    collections::HashMap,
    fmt::Display,
    io::{BufRead, Cursor, Error, ErrorKind, Read, Seek},
};

use self::types::WinInTypeItem;

use super::TraceHeaderType;
use bitflags::bitflags;
use serde::Serialize;
use uuid::{uuid, Uuid};

use crate::helper::*;

const MODERN_EVENT_HEADER_SIZE: usize = 80;

#[derive(Debug)]
pub struct ModernEventError {
    kind: ErrorType,
    source: Option<Box<dyn std::error::Error + 'static>>,
    description: Option<Box<dyn core::fmt::Debug>>,
}
impl ModernEventError {
    fn new(kind: ErrorType) -> ModernEventError {
        ModernEventError {
            kind,
            source: None,
            description: None,
        }
    }
    fn new_with_source<S: std::error::Error + 'static>(
        kind: ErrorType,
        source: S,
    ) -> ModernEventError {
        ModernEventError {
            kind,
            source: Some(Box::new(source)),
            description: None,
        }
    }
    fn new_with_description<D: core::fmt::Debug + 'static>(
        kind: ErrorType,
        description: D,
    ) -> ModernEventError {
        ModernEventError {
            kind,
            source: None,
            description: Some(Box::new(description)),
        }
    }
    fn invalid_payload<D: std::fmt::Debug + 'static>(e: D) -> ModernEventError {
        ModernEventError {
            kind: ErrorType::InvalidPayload,
            source: None,
            description: Some(Box::new(e)),
        }
    }

    pub fn kind(&self) -> ErrorType {
        self.kind
    }
}
impl Display for ModernEventError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ErrorType::Io => {
                write!(f, "A error occured while reading data to parse an event")?;
                if let Some(s) = &self.source {
                    write!(f, ": {s}")?;
                }
                Ok(())
            }
            ErrorType::InvalidHeader => write!(f, "Failed to parse modern event header."),
            ErrorType::InvalidPayload => {
                write!(f, "Failed to parse a event payload item")?;
                if let Some(d) = &self.description {
                    write!(f, ": {:?}", d)?;
                }
                Ok(())
            }
            ErrorType::ParseError => write!(f, "A error occured while parsing an event."),
            ErrorType::NotSupported => {
                write!(f, "Encountered modern event with unsuppored format")?;
                if let Some(d) = &self.description {
                    write!(f, ": {:?}", d)?;
                }
                Ok(())
            }
        }
    }
}
impl From<std::io::Error> for ModernEventError {
    fn from(value: std::io::Error) -> Self {
        ModernEventError::new_with_source(ErrorType::Io, value)
    }
}
impl std::error::Error for ModernEventError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match &self.source {
            Some(e) => Some(e.as_ref()),
            None => None,
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum ErrorType {
    Io,
    InvalidHeader,
    InvalidPayload,
    ParseError,
    NotSupported,
}

/// A modern event
///
/// Usually a event produced by a manifest based provider.
///
/// Since the API is backwards compatible, modern events can
/// also be generated by other providers (MOF based).
#[derive(Debug)]
pub struct ModernEvent {
    pub header: ModernEventHeader,
    pub extended_header: Option<Vec<u8>>,
    pub payload: Cursor<Vec<u8>>,
}

impl ModernEvent {
    /// Parse a ModernEvent from Windows native binary representation
    pub(crate) fn parse<R: Read + Seek>(buf: &mut R) -> Result<ModernEvent, ModernEventError> {
        let header = ModernEventHeader::parse(buf)?;

        if header.event_flags.contains(Flags::ExtendedInfo) {
            log::warn!("Events containing extended header items not jet supported.");
            return Err(ModernEventError::new_with_description(
                ErrorType::NotSupported,
                "Extended header items not jet supported!",
            ));
        }

        let payload_size = header.size - header.length() as u16;

        let mut payload: Vec<u8> = vec![0u8; payload_size as usize];

        buf.read_exact(&mut payload)?;

        let payload = Cursor::new(payload);

        Ok(ModernEvent {
            header,
            extended_header: None,
            payload,
        })
    }

    pub(crate) fn read_payload_item(
        &mut self,
        in_type: WinInType,
        size: Option<u16>,
    ) -> Result<WinInTypeItem, ModernEventError> {
        match in_type {
            WinInType::Int8 => {
                let mut buf = [0_u8; 1];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Int8(buf[0] as i8))
            }
            WinInType::UInt8 => {
                let mut buf = [0_u8; 1];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::UInt8(buf[0]))
            }
            WinInType::Int16 => {
                let mut buf = [0_u8; 2];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Int16(i16::from_le_bytes(buf)))
            }
            WinInType::UInt16 => {
                let mut buf = [0_u8; 2];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::UInt16(u16::from_le_bytes(buf)))
            }
            WinInType::Int32 => {
                let mut buf = [0_u8; 4];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Int32(i32::from_le_bytes(buf)))
            }
            WinInType::UInt32 => {
                let mut buf = [0_u8; 4];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::UInt32(u32::from_le_bytes(buf)))
            }
            WinInType::Int64 => {
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Int64(i64::from_le_bytes(buf)))
            }
            WinInType::UInt64 => {
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::UInt64(u64::from_le_bytes(buf)))
            }
            WinInType::Float => {
                let mut buf = [0_u8; 4];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Float(f32::from_le_bytes(buf)))
            }
            WinInType::Double => {
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Double(f64::from_le_bytes(buf)))
            }
            WinInType::Boolean => {
                let mut buf = [0_u8; 4];
                self.payload.read_exact(&mut buf)?;
                let x = u32::from_le_bytes(buf);
                if x == 0 {
                    Ok(WinInTypeItem::Boolean(false))
                } else {
                    Ok(WinInTypeItem::Boolean(true))
                }
            }
            WinInType::AnsiString => {
                let mut buf = Vec::new();
                self.payload.read_until(0_u8, &mut buf)?;
                use core::ffi::CStr;
                let cstr =
                    CStr::from_bytes_with_nul(&buf).map_err(ModernEventError::invalid_payload)?;
                Ok(WinInTypeItem::AnsiString(
                    cstr.to_string_lossy().into_owned(),
                ))
            }
            WinInType::UnicodeString => {
                let s = read_utf16_string(&mut self.payload)?;
                Ok(WinInTypeItem::UnicodeString(s))
            }
            WinInType::Binary => {
                let Some(size) = size else {
                    return Err(ModernEventError::new(ErrorType::ParseError));
                };
                log::trace!("reading binary payload with size {size}");
                let mut buf: Vec<u8> = vec![0; size as usize];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Binary(buf))
            }
            WinInType::Pointer => {
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Pointer(u64::from_le_bytes(buf)))
            }
            WinInType::SizeT => {
                // TODO support different sizes
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::SizeT(u64::from_le_bytes(buf)))
            }
            WinInType::Guid => {
                let mut buf = [0_u8; 16];
                self.payload.read_exact(&mut buf)?;
                let guid = Uuid::from_bytes_le(buf);
                Ok(WinInTypeItem::Guid(guid))
            }
            WinInType::Sid => {
                let sid = types::Sid::parse(&mut self.payload)?;
                Ok(WinInTypeItem::Sid(sid))
            }
            WinInType::Filetime => {
                let mut buf = [0_u8; 8];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Filetime(buf.into()))
            }
            WinInType::Systemtime => {
                let mut buf = [0_u8; 16];
                self.payload.read_exact(&mut buf)?;
                Ok(WinInTypeItem::Systemtime(
                    buf.try_into().map_err(ModernEventError::invalid_payload)?,
                ))
            }
        }
    }

    #[cfg(not(feature = "proc-etw-manifest"))]
    /// Wraps the generic event in a concise event
    ///
    /// Returns always None if no manifests have been included with proc-etw-manifest.
    pub fn into_contained_event(self) -> Option<Box<dyn Event>> {
        None
    }
}

pub trait Event: core::ops::Deref<Target = ModernEvent> + core::ops::DerefMut {
    fn get_provider_name(&self) -> &str;
    fn get_event_task_name(&self) -> Option<&str>;
    fn get_event_symbol(&self) -> Option<&str>;
    fn get_payload_items(&mut self) -> Option<&HashMap<&'static str, WinInTypeItem>>;
}

#[cfg(feature = "proc-etw-manifest")]
proc_etw_manifest::include_manifests!("./manifest/enabled");

/// Header of a modern event
#[repr(C)]
#[derive(Debug, Clone, Serialize)]
pub struct ModernEventHeader {
    /// Total size of the event (not including potential padding)
    pub size: u16,
    pub header_type: TraceHeaderType,
    pub flags: u8,
    pub event_flags: Flags,
    pub event_properties: u16,
    /// Thread id the event occured in
    pub thread_id: u32,
    /// Process id the event occured in
    pub process_id: u32,
    pub timestamp: types::EtwTimestamp,
    /// The GUID of the provider
    pub provider_id: Uuid,
    /// Event descriptor
    pub event_descriptor: EventDescriptor,
    /// Placeholder for the union describing kernel or processor time
    pub time_union: u64,
    pub activity_id: Uuid,
}

/// Event description
#[derive(Debug, Clone, Serialize)]
pub struct EventDescriptor {
    /// Event id
    ///
    /// Forms the distinct event type together with the version and the provider GUID.
    pub id: u16,
    /// Version of the event
    pub version: u8,
    /// Channel id
    pub channel: u8,
    /// Log level of this event
    pub level: u8,
    /// Opcode of this event (if existent)
    pub opcode: u8,
    /// The event-task this event describes
    pub task: u16,
    /// Flags for filters
    pub keywords: u64,
}

impl EventDescriptor {
    /// Parse an EventDescriptor from Windows native binary representation
    fn parse(buf: [u8; 16]) -> EventDescriptor {
        let id = u16_from_le_slice(&buf[0..2]).unwrap();
        let version = buf[2];
        let channel = buf[3];
        let level = buf[4];
        let opcode = buf[5];
        let task = u16_from_le_slice(&buf[6..8]).unwrap();
        let keywords = u64_from_le_slice(&buf[8..]).unwrap();
        EventDescriptor {
            id,
            version,
            channel,
            level,
            opcode,
            task,
            keywords,
        }
    }
}

impl ModernEventHeader {
    /// Parse a ModernEventHeader from Windows native binary representation
    pub fn parse<T: Read + Seek>(buf: &mut T) -> Result<ModernEventHeader, ModernEventError> {
        let mut bytes = [0; MODERN_EVENT_HEADER_SIZE];
        buf.read_exact(&mut bytes)?;
        let size = u16_from_le_slice(&bytes[0..2])?;

        let header_type = TraceHeaderType::try_from(bytes[2]).map_err(|_| {
            Error::new(
                ErrorKind::InvalidData,
                "encountered unknown TraceHeaderType!",
            )
        })?;

        if !matches!(
            header_type,
            TraceHeaderType::ModernEvent32 | TraceHeaderType::ModernEvent64
        ) {
            return Err(ModernEventError::new(ErrorType::InvalidHeader));
        }

        let flags = bytes[3];
        let event_flags = Flags::from_bits(u16_from_le_slice(&bytes[4..6])?).ok_or(Error::new(
            ErrorKind::InvalidData,
            "encountered unknown event flag!",
        ))?;

        let event_properties = u16_from_le_slice(&bytes[6..8])?;
        let thread_id = u32_from_le_slice(&bytes[8..12])?;
        let process_id = u32_from_le_slice(&bytes[12..16])?;

        let timestamp =
            types::EtwTimestamp::EtwTime(types::EtwTime(u64_from_le_slice(&bytes[16..24])?));

        let provider_id = Uuid::from_slice_le(&bytes[24..40]).unwrap(); // errors if slice to short

        // let event_descriptor =
        //     EventDescriptor(u128::from_le_bytes(bytes[40..56].try_into().unwrap()));

        let event_descriptor = EventDescriptor::parse(bytes[40..56].try_into().unwrap());

        let time_union = u64_from_le_slice(&bytes[56..64])?;

        let activity_id = Uuid::from_slice_le(&bytes[64..80]).unwrap();

        Ok(ModernEventHeader {
            size,
            header_type,
            flags,
            event_flags,
            event_properties,
            thread_id,
            process_id,
            timestamp,
            provider_id,
            event_descriptor,
            time_union,
            activity_id,
        })
    }

    /// Return the length of the header
    pub fn length(&self) -> usize {
        // TODO: extended header
        MODERN_EVENT_HEADER_SIZE
    }
}

impl From<crate::helper::ParseError> for ModernEventError {
    fn from(_: crate::helper::ParseError) -> Self {
        ModernEventError {
            kind: ErrorType::ParseError,
            source: None,
            description: None,
        }
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, Serialize)]
    pub struct Flags: u16 {
        const ExtendedInfo = 0x0001;
        const PrivateSession = 0x0002;
        const StringOnly = 0x0004;
        const TraceMessage = 0x0008;
        const NoCputime = 0x0010;
        const Header32Bit = 0x0020;
        const Header64Bit = 0x0040;
        const DecodeGuid = 0x0080;
        const ClassicHeader = 0x0100;
        const ProcessorIndex = 0x0200;
    }
}

#[allow(unused)]
pub(crate) enum WinInType {
    Int8,
    UInt8,
    Int16,
    UInt16,
    Int32,
    UInt32,
    Int64,
    UInt64,
    Float,
    Double,
    Boolean,
    AnsiString,
    UnicodeString,
    Binary,
    Pointer,
    SizeT,
    Guid,
    Sid,
    Filetime,
    Systemtime,
}

pub mod types {
    //! Types uniqe to modern events

    use filetime_type::FileTime;
    use serde::Serialize;
    use std::fmt::Display;
    use uuid::Uuid;

    mod sid;
    pub use sid::Sid;

    mod etw_time;
    pub use etw_time::*;

    use crate::types::SystemTime;

    /// Win InType Items
    // TODO improve memory efficiency
    #[derive(Debug, Clone)]
    pub enum WinInTypeItem {
        Int8(i8),
        UInt8(u8),
        Int16(i16),
        UInt16(u16),
        Int32(i32),
        UInt32(u32),
        Int64(i64),
        UInt64(u64),
        Float(f32),
        Double(f64),
        Boolean(bool),
        AnsiString(String),
        UnicodeString(String),
        Binary(Vec<u8>),
        /// Pointer on 64bit machines
        Pointer(u64),
        SizeT(u64),
        Guid(Uuid),
        Sid(Sid),
        Filetime(FileTime),
        Systemtime(SystemTime),
    }

    impl Serialize for WinInTypeItem {
        fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: serde::Serializer,
        {
            match self {
                WinInTypeItem::Int8(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 0, "i8", x)
                }
                WinInTypeItem::UInt8(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 1, "u8", x)
                }
                WinInTypeItem::Int16(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 2, "i16", x)
                }
                WinInTypeItem::UInt16(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 3, "u16", x)
                }
                WinInTypeItem::Int32(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 4, "i32", x)
                }
                WinInTypeItem::UInt32(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 5, "u32", x)
                }
                WinInTypeItem::Int64(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 6, "i64", x)
                }
                WinInTypeItem::UInt64(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 7, "u64", x)
                }
                WinInTypeItem::Float(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 8, "float", x)
                }
                WinInTypeItem::Double(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 9, "double", x)
                }
                WinInTypeItem::Boolean(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 10, "bool", x)
                }
                WinInTypeItem::AnsiString(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 11, "ansi_string", x)
                }
                WinInTypeItem::UnicodeString(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 12, "unicode_string", x)
                }
                WinInTypeItem::Binary(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 13, "binary", x)
                }
                WinInTypeItem::Pointer(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 14, "pointer", x)
                }
                WinInTypeItem::SizeT(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 15, "size_t", x)
                }
                WinInTypeItem::Guid(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 16, "guid", x)
                }
                WinInTypeItem::Sid(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 17, "sid", x)
                }
                WinInTypeItem::Filetime(x) => serializer.serialize_newtype_variant(
                    "WinInTypeItem",
                    18,
                    "time",
                    &x.to_datetime(),
                ),
                WinInTypeItem::Systemtime(x) => {
                    serializer.serialize_newtype_variant("WinInTypeItem", 19, "time", x)
                }
            }
        }
    }

    impl Display for WinInTypeItem {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                WinInTypeItem::Int8(x) => write!(f, "{}", x),
                WinInTypeItem::UInt8(x) => write!(f, "{}", x),
                WinInTypeItem::Int16(x) => write!(f, "{}", x),
                WinInTypeItem::UInt16(x) => write!(f, "{}", x),
                WinInTypeItem::Int32(x) => write!(f, "{}", x),
                WinInTypeItem::UInt32(x) => write!(f, "{}", x),
                WinInTypeItem::Int64(x) => write!(f, "{}", x),
                WinInTypeItem::UInt64(x) => write!(f, "{}", x),
                WinInTypeItem::Float(x) => write!(f, "{}", x),
                WinInTypeItem::Double(x) => write!(f, "{}", x),
                WinInTypeItem::Boolean(x) => write!(f, "{}", x),
                WinInTypeItem::AnsiString(x) => write!(f, "{}", x),
                WinInTypeItem::UnicodeString(x) => write!(f, "{}", x),
                WinInTypeItem::Binary(_) => write!(f, "[Binary]"), // TODO
                WinInTypeItem::Pointer(x) => write!(f, "{}", x),
                WinInTypeItem::SizeT(x) => write!(f, "{}", x),
                WinInTypeItem::Guid(x) => write!(f, "{}", x),
                WinInTypeItem::Sid(x) => write!(f, "{}", x),
                WinInTypeItem::Filetime(x) => write!(f, "{}", x),
                WinInTypeItem::Systemtime(x) => write!(f, "{:?}", x),
            }
        }
    }
}
