// pub mod provider;

use std::io::{Error, ErrorKind, Read, Result, Seek};

use super::TraceHeaderType;
use bitflags::bitflags;
use uuid::{uuid, Uuid};

use crate::helper::{u16_from_le_slice, u32_from_le_slice, u64_from_le_slice};

const MODERN_EVENT_HEADER_SIZE: usize = 80;

/// A modern event
///
/// Usually a event produced by a manifest based provider.
///
/// Since the API is backwards compatible, modern events can
/// also be generated by other providers (MOF based).
#[derive(Debug)]
pub struct ModernEvent {
    pub header: ModernEventHeader,
    pub extended_header: Option<Vec<u8>>,
    pub payload: Vec<u8>,
}

impl ModernEvent {
    /// Parse a ModernEvent from Windows native binary representation
    pub(crate) fn parse<R: Read + Seek>(buf: &mut R) -> Result<ModernEvent> {
        let header = ModernEventHeader::parse(buf)?;

        if header.event_flags.contains(Flags::ExtendedInfo) {
            log::warn!("Events containing extended header items not jet supported.");
            todo!();
        }

        let payload_size = header.size - header.length() as u16;

        let mut payload: Vec<u8> = vec![0u8; payload_size as usize];

        buf.read_exact(&mut payload)?;

        Ok(ModernEvent {
            header,
            extended_header: None,
            payload,
        })
    }
}

proc_etw_manifest::include_manifests!("./manifest");

// const TEST_GUID: Uuid = uuid!("{00000000-0000-0000-0000-ffff00000000}");

// impl ModernEvent {
//     pub fn get_provider_name(&self) -> Option<&str> {
//         match self.header.provider_id {
//             TEST_GUID => Some("test"),
//             _ => None,
//         }
//     }
// }

/// Header of a modern event
#[repr(C)]
#[derive(Debug)]
pub struct ModernEventHeader {
    /// Total size of the event (not including potential padding)
    pub size: u16,
    pub header_type: TraceHeaderType,
    pub flags: u8,
    pub event_flags: Flags,
    pub event_properties: u16,
    /// Thread id the event occured in
    pub thread_id: u32,
    /// Process id the event occured in
    pub process_id: u32,
    pub timestamp: u64,
    /// The GUID of the provider
    pub provider_id: Uuid,
    /// Event descriptor
    pub event_descriptor: EventDescriptor,
    /// Placeholder for the union describing kernel or processor time
    pub time_union: u64,
    pub activity_id: Uuid,
}

/// WIP Placeholder
#[derive(Debug)]
pub struct EventDescriptor {
    /// Event id
    ///
    /// Forms the distinct event type together with the version and the provider GUID.
    pub id: u16,
    /// Version of the event
    pub version: u8,
    /// Channel id
    pub channel: u8,
    /// Log level of this event
    pub level: u8,
    /// Opcode of this event (if existent)
    pub opcode: u8,
    /// The event-task this event describes
    pub task: u16,
    /// Flags for filters
    pub keywords: u64,
}

impl EventDescriptor {
    /// Parse an EventDescriptor from Windows native binary representation
    fn parse(buf: [u8; 16]) -> EventDescriptor {
        let id = u16_from_le_slice(&buf[0..2]).unwrap();
        let version = buf[2];
        let channel = buf[3];
        let level = buf[4];
        let opcode = buf[5];
        let task = u16_from_le_slice(&buf[6..8]).unwrap();
        let keywords = u64_from_le_slice(&buf[8..]).unwrap();
        EventDescriptor {
            id,
            version,
            channel,
            level,
            opcode,
            task,
            keywords,
        }
    }
}

impl ModernEventHeader {
    /// Parse a ModernEventHeader from Windows native binary representation
    pub fn parse<T: Read + Seek>(buf: &mut T) -> Result<ModernEventHeader> {
        let mut bytes = [0; MODERN_EVENT_HEADER_SIZE];
        buf.read_exact(&mut bytes)?;
        let size = u16_from_le_slice(&bytes[0..2])?;

        let header_type = TraceHeaderType::try_from(bytes[2]).map_err(|_| {
            Error::new(
                ErrorKind::InvalidData,
                "encountered unknown TraceHeaderType!",
            )
        })?;

        if !matches!(
            header_type,
            TraceHeaderType::ModernEvent32 | TraceHeaderType::ModernEvent64
        ) {
            return Err(Error::new(
                ErrorKind::InvalidData,
                "trying to parse ModernEventHeader, but found other TraceHeaderType!",
            ));
        }

        let flags = bytes[3];
        let event_flags = Flags::from_bits(u16_from_le_slice(&bytes[4..6])?).ok_or(Error::new(
            ErrorKind::InvalidData,
            "encountered unknown event flag!",
        ))?;

        let event_properties = u16_from_le_slice(&bytes[6..8])?;
        let thread_id = u32_from_le_slice(&bytes[8..12])?;
        let process_id = u32_from_le_slice(&bytes[12..16])?;

        let timestamp = u64_from_le_slice(&bytes[16..24])?;

        let provider_id = Uuid::from_slice_le(&bytes[24..40]).unwrap(); // errors if slice to short

        // let event_descriptor =
        //     EventDescriptor(u128::from_le_bytes(bytes[40..56].try_into().unwrap()));

        let event_descriptor = EventDescriptor::parse(bytes[40..56].try_into().unwrap());

        let time_union = u64_from_le_slice(&bytes[56..64])?;

        let activity_id = Uuid::from_slice_le(&bytes[64..80]).unwrap();

        Ok(ModernEventHeader {
            size,
            header_type,
            flags,
            event_flags,
            event_properties,
            thread_id,
            process_id,
            timestamp,
            provider_id,
            event_descriptor,
            time_union,
            activity_id,
        })
    }

    /// Return the length of the header
    pub fn length(&self) -> usize {
        // TODO: extended header
        MODERN_EVENT_HEADER_SIZE
    }
}

impl From<crate::helper::ParseError> for Error {
    fn from(_: crate::helper::ParseError) -> Self {
        Error::new(
            ErrorKind::Other,
            "Oops, error parsing, a wrong slice size was used somewhere.",
        )
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug)]
    pub struct Flags: u16 {
        const ExtendedInfo = 0x0001;
        const PrivateSession = 0x0002;
        const StringOnly = 0x0004;
        const TraceMessage = 0x0008;
        const NoCputime = 0x0010;
        const Header32Bit = 0x0020;
        const Header64Bit = 0x0040;
        const DecodeGuid = 0x0080;
        const ClassicHeader = 0x0100;
        const ProcessorIndex = 0x0200;
    }
}
