use std::io::{Error, ErrorKind, Read, Result, Seek};

use super::TraceHeaderType;
use uuid::Uuid;

use crate::helper::{u16_from_le_slice, u32_from_le_slice, u64_from_le_slice};

const MODERN_EVENT_HEADER_SIZE: usize = 80;

/// A modern event
///
/// Usually a event produced by a manifest based provider.
///
/// Since the API is backwards compatible, modern events can
/// also be generated by other providers (MOF based).
#[derive(Debug)]
pub struct ModernEvent {
    pub header: ModernEventHeader,
    pub extended_header: Vec<u8>,
    pub payload: Vec<u8>,
}

impl ModernEvent {
    pub(crate) fn parse<R: Read + Seek>(buf: &mut R) -> Result<ModernEvent> {
        let header = ModernEventHeader::parse(buf)?;

        let payload_size = header.size - header.length() as u16;

        let mut payload: Vec<u8> = vec![0u8; payload_size as usize];

        buf.read_exact(&mut payload)?;

        Ok(ModernEvent {
            header,
            extended_header: Vec::new(),
            payload,
        })
    }
}

/// Header of a modern event
#[repr(C)]
#[derive(Debug)]
pub struct ModernEventHeader {
    pub size: u16,
    pub header_type: TraceHeaderType,
    pub flags: u8,
    pub event_flags: u16,
    pub event_properties: u16,
    pub thread_id: u32,
    pub process_id: u32,
    pub timestamp: u64,
    pub provider_id: Uuid,
    pub event_descriptor: EventDescriptor,
    /// Placeholder for the union describing kernel or processor time
    pub time_union: u64,
    pub activity_id: Uuid,
}

/// WIP Placeholder
#[derive(Debug)]
pub struct EventDescriptor(u128);

impl ModernEventHeader {
    pub fn parse<T: Read + Seek>(buf: &mut T) -> Result<ModernEventHeader> {
        let mut bytes = [0; MODERN_EVENT_HEADER_SIZE];
        buf.read_exact(&mut bytes)?;
        let size = u16_from_le_slice(&bytes[0..2])?;

        let header_type = TraceHeaderType::try_from(bytes[2]).map_err(|_| {
            Error::new(
                ErrorKind::InvalidData,
                "encountered unknown TraceHeaderType!",
            )
        })?;

        if !matches!(
            header_type,
            TraceHeaderType::ModernEvent32 | TraceHeaderType::ModernEvent64
        ) {
            return Err(Error::new(
                ErrorKind::InvalidData,
                "trying to parse ModernEventHeader, but found other TraceHeaderType!",
            ));
        }

        let flags = bytes[3];
        let event_flags = u16_from_le_slice(&bytes[4..6])?;

        let event_properties = u16_from_le_slice(&bytes[6..8])?;
        let thread_id = u32_from_le_slice(&bytes[8..12])?;
        let process_id = u32_from_le_slice(&bytes[12..16])?;

        let timestamp = u64_from_le_slice(&bytes[16..24])?;

        let provider_id = Uuid::from_slice_le(&bytes[24..40]).unwrap(); // errors if slice to short

        let event_descriptor =
            EventDescriptor(u128::from_le_bytes(bytes[40..56].try_into().unwrap()));

        let time_union = u64_from_le_slice(&bytes[56..64])?;

        let activity_id = Uuid::from_slice_le(&bytes[64..80]).unwrap();

        Ok(ModernEventHeader {
            size,
            header_type,
            flags,
            event_flags,
            event_properties,
            thread_id,
            process_id,
            timestamp,
            provider_id,
            event_descriptor,
            time_union,
            activity_id,
        })
    }

    /// Return the length of the header
    pub fn length(&self) -> usize {
        // TODO: extended header
        MODERN_EVENT_HEADER_SIZE
    }
}

impl From<crate::helper::ParseError> for Error {
    fn from(_: crate::helper::ParseError) -> Self {
        Error::new(
            ErrorKind::Other,
            "Oops, error parsing, a wrong slice size was used somewhere.",
        )
    }
}
