use super::{Guid, TraceHeaderType};

pub struct ModernEvent {
    pub header: ModernEventHeader,
    pub extended_header: Vec<u8>,
    pub payload: Vec<u8>,
}

/// A modern event
///
/// Usually a event produced by a manifest based provider.
///
/// Since the API is backwards compatible, modern events can
/// also be generated by other providers (MOF based).
#[repr(C)]
pub struct ModernEventHeader {
    pub size: u16,
    pub header_type: TraceHeaderType,
    pub flags: u8,
    pub event_flags: u16,
    pub event_properties: u16,
    pub thread_id: u32,
    pub process_id: u32,
    pub timestamp: u64,
    pub provider_id: Guid,
    pub event_descriptor: EventDescriptor,
    /// Placeholder for the union describing kernel or processor time
    pub time_union: u64,
    pub activity_id: Guid,
}

/// WIP Placeholder
pub struct EventDescriptor(u128);
